// The seed bank: the guaranteed supply of joke premises.
//
// This is plain data, no logic. The joke writer turns a premise into an
// original meme — the premise itself is never posted verbatim. Add a line here
// and it enters rotation on the next run; nothing else needs to change.
//
// `photo` is the stock-photo search term the joke will sit on. Keep it simple
// and literal ("tired cat", "empty wallet") — stock search is bad at abstractions.
//
// Reddit fuel (lib/memeFuel.ts) tops this up with fresher sparks, but the page
// survives entirely on this file if Reddit is down or all its titles get filtered.

export interface Seed {
  lane: string;
  premise: string;
  photo: string;
}

export const SEEDS: Seed[] = [
  // --- RELATABLE: general everyday life ----------------------------------
  { lane: "RELATABLE", premise: "rehearsing an argument in the shower that will never happen", photo: "shower head water" },
  { lane: "RELATABLE", premise: "saying 'you too' when the waiter says enjoy your meal", photo: "restaurant waiter" },
  { lane: "RELATABLE", premise: "opening the fridge again hoping new food appeared", photo: "open fridge at night" },
  { lane: "RELATABLE", premise: "pretending to look at products until the shop assistant leaves", photo: "person in supermarket aisle" },
  { lane: "RELATABLE", premise: "the panic of hearing your own voice in a recording", photo: "person covering ears" },
  { lane: "RELATABLE", premise: "waving back at someone who was waving at the person behind you", photo: "person waving street" },
  { lane: "RELATABLE", premise: "putting laundry on the chair instead of away, forever", photo: "clothes piled on chair" },
  { lane: "RELATABLE", premise: "restarting a series you already watched instead of the new one you saved", photo: "person watching tv remote" },
  { lane: "RELATABLE", premise: "walking into a room and forgetting why immediately", photo: "confused person doorway" },
  { lane: "RELATABLE", premise: "the specific rage of a tangled pair of earphones", photo: "tangled headphones" },
  { lane: "RELATABLE", premise: "agreeing to plans in two weeks then dreading them for two weeks", photo: "calendar planner desk" },
  { lane: "RELATABLE", premise: "checking your phone and immediately forgetting what you checked", photo: "person looking at phone" },
  { lane: "RELATABLE", premise: "pretending the self-checkout machine is not yelling at you", photo: "self checkout machine" },
  { lane: "RELATABLE", premise: "the 3 second gap before you remember you already replied", photo: "person thinking phone" },
  { lane: "RELATABLE", premise: "adding things to a cart you have no intention of buying", photo: "online shopping laptop" },
  { lane: "RELATABLE", premise: "hearing your name and turning around for nobody", photo: "crowded street people" },
  { lane: "RELATABLE", premise: "your phone at 1 percent lasting longer than it did at 40", photo: "phone low battery" },
  { lane: "RELATABLE", premise: "picking the shortest queue and it becoming the slowest queue", photo: "supermarket queue" },
  { lane: "RELATABLE", premise: "smiling at a dog and ignoring its owner completely", photo: "dog on a walk" },
  { lane: "RELATABLE", premise: "finding money in an old jacket like you won something", photo: "hand in jacket pocket" },
  { lane: "RELATABLE", premise: "the deep silence after you send a voice note", photo: "phone voice message" },
  { lane: "RELATABLE", premise: "saying 'let me know if you need anything' and praying they do not", photo: "person texting couch" },
  { lane: "RELATABLE", premise: "holding a sneeze in a quiet room", photo: "quiet library" },
  { lane: "RELATABLE", premise: "reading the same paragraph four times and absorbing nothing", photo: "person reading book" },
  { lane: "RELATABLE", premise: "the sound of the doorbell when you ordered nothing", photo: "front door bell" },
  { lane: "RELATABLE", premise: "trying to look busy when someone walks past your screen", photo: "person at laptop office" },
  { lane: "RELATABLE", premise: "your alarm on a day off going off out of pure spite", photo: "alarm clock bedside" },
  { lane: "RELATABLE", premise: "nodding along to directions you stopped following instantly", photo: "two people talking street" },
  { lane: "RELATABLE", premise: "being unable to spell a word you have written a thousand times", photo: "person writing notebook" },
  { lane: "RELATABLE", premise: "the confidence of singing alone in the car", photo: "person driving singing" },
  { lane: "RELATABLE", premise: "queueing a podcast and hearing none of it", photo: "person walking headphones" },
  { lane: "RELATABLE", premise: "arriving early and sitting in the car until the exact minute", photo: "person sitting in car" },
  { lane: "RELATABLE", premise: "the 30 seconds of regret after sending a long message", photo: "person staring at phone" },
  { lane: "RELATABLE", premise: "clearing 40 browser tabs and opening 40 more", photo: "laptop screen tabs" },
  { lane: "RELATABLE", premise: "pretending to understand the wine description", photo: "wine glass restaurant" },

  // --- WORK: jobs, meetings, offices --------------------------------------
  { lane: "WORK", premise: "a meeting that could have been one short message", photo: "boring office meeting" },
  { lane: "WORK", premise: "typing, deleting, and retyping one email sentence eleven times", photo: "person typing laptop" },
  { lane: "WORK", premise: "saying 'per my last email' while internally screaming", photo: "frustrated person computer" },
  { lane: "WORK", premise: "looking extremely busy for the last 20 minutes of the day", photo: "office clock desk" },
  { lane: "WORK", premise: "the fake laugh you do at a manager's joke", photo: "office people laughing" },
  { lane: "WORK", premise: "'quick call?' arriving with no context at 4:55pm", photo: "phone ringing desk" },
  { lane: "WORK", premise: "being on mute for an entire brilliant point", photo: "video call laptop" },
  { lane: "WORK", premise: "your camera turning on before you were ready", photo: "person surprised webcam" },
  { lane: "WORK", premise: "agreeing to a deadline you know is fantasy", photo: "calendar deadline desk" },
  { lane: "WORK", premise: "the Monday morning walk from the car to the door", photo: "office building entrance" },
  { lane: "WORK", premise: "opening a spreadsheet and closing it immediately", photo: "spreadsheet on screen" },
  { lane: "WORK", premise: "someone replying all to a 200 person email", photo: "inbox full of emails" },
  { lane: "WORK", premise: "the printer choosing violence on the one urgent day", photo: "office printer" },
  { lane: "WORK", premise: "'does anyone have any questions' and the eternal silence", photo: "empty meeting room" },
  { lane: "WORK", premise: "working from home in a shirt and pyjama trousers", photo: "person working from home" },
  { lane: "WORK", premise: "the 9am energy versus the 2pm energy", photo: "tired person at desk" },
  { lane: "WORK", premise: "pretending you remember the name of the person greeting you", photo: "office corridor people" },
  { lane: "WORK", premise: "your one day off and everything breaks", photo: "phone notifications desk" },
  { lane: "WORK", premise: "taking notes you will never read again", photo: "notebook pen meeting" },
  { lane: "WORK", premise: "the sound of a colleague opening crisps in a silent office", photo: "quiet office desks" },
  { lane: "WORK", premise: "saying 'circle back' because you have no idea", photo: "whiteboard office meeting" },
  { lane: "WORK", premise: "closing your laptop like it owes you money", photo: "closing laptop desk" },
  { lane: "WORK", premise: "the Sunday evening feeling arriving at 4pm", photo: "sunset window sunday" },
  { lane: "WORK", premise: "being asked to be more proactive by someone blocking you", photo: "office meeting tense" },
  { lane: "WORK", premise: "your inbox after two days of annual leave", photo: "overflowing inbox laptop" },
  { lane: "WORK", premise: "the coffee machine being the only reason you came in", photo: "office coffee machine" },
  { lane: "WORK", premise: "a team building exercise nobody asked for", photo: "team building activity" },
  { lane: "WORK", premise: "forwarding an email instead of solving anything", photo: "person at computer email" },
  { lane: "WORK", premise: "the one person who says 'well, it's Monday' every Monday", photo: "office kitchen chat" },
  { lane: "WORK", premise: "logging off exactly on time for the first time ever", photo: "empty office evening" },
  { lane: "WORK", premise: "'sorry for the delay' after four business days", photo: "laptop email screen" },
  { lane: "WORK", premise: "your headphones on with nothing playing so nobody talks to you", photo: "person headphones desk" },
  { lane: "WORK", premise: "asking a question you already know the answer to in a meeting", photo: "office meeting table" },
  { lane: "WORK", premise: "the panic when the boss walks behind your chair", photo: "office worker screen" },
  { lane: "WORK", premise: "that one recurring meeting nobody can cancel", photo: "calendar recurring meeting" },

  // --- SLEEP: nights, alarms, tiredness ------------------------------------
  { lane: "SLEEP", premise: "setting five alarms and ignoring every single one", photo: "alarm clock morning" },
  { lane: "SLEEP", premise: "going to bed early and staying awake until 2am anyway", photo: "person awake in bed" },
  { lane: "SLEEP", premise: "your brain replaying an embarrassing moment from 2013 at 3am", photo: "person awake at night" },
  { lane: "SLEEP", premise: "'just five more minutes' costing you ninety", photo: "person sleeping in bed" },
  { lane: "SLEEP", premise: "being exhausted all day and wide awake at bedtime", photo: "tired person yawning" },
  { lane: "SLEEP", premise: "the perfect sleep position existing for four seconds", photo: "person in bed pillow" },
  { lane: "SLEEP", premise: "waking up one minute before the alarm and feeling robbed", photo: "alarm clock bedside table" },
  { lane: "SLEEP", premise: "scrolling until your phone hits you in the face", photo: "phone in bed dark" },
  { lane: "SLEEP", premise: "napping for 20 minutes and waking up in a new century", photo: "person napping sofa" },
  { lane: "SLEEP", premise: "the cold side of the pillow being the only good thing left", photo: "pillow bed white" },
  { lane: "SLEEP", premise: "your body deciding 5am is the new wake up time on a Saturday", photo: "sunrise bedroom window" },
  { lane: "SLEEP", premise: "one foot out of the duvet to regulate your entire temperature", photo: "duvet bed feet" },
  { lane: "SLEEP", premise: "remembering you have work tomorrow at 11:58pm", photo: "clock at night dark" },
  { lane: "SLEEP", premise: "the dream you desperately want to get back into", photo: "person sleeping peacefully" },
  { lane: "SLEEP", premise: "falling asleep instantly the second the alarm should ring", photo: "sleeping person morning light" },
  { lane: "SLEEP", premise: "coffee doing absolutely nothing anymore", photo: "coffee cup morning" },
  { lane: "SLEEP", premise: "going to bed angry about the amount of sleep you will get", photo: "person in bed phone" },
  { lane: "SLEEP", premise: "the 4pm crash arriving on schedule", photo: "tired person desk afternoon" },
  { lane: "SLEEP", premise: "waking up more tired than when you went to bed", photo: "person rubbing eyes bed" },
  { lane: "SLEEP", premise: "snoozing so many times the alarm gives up", photo: "phone alarm bed" },
  { lane: "SLEEP", premise: "a sudden burst of energy at exactly 11pm", photo: "person awake night lamp" },
  { lane: "SLEEP", premise: "the specific horror of waking up and the room being bright", photo: "bright bedroom morning" },
  { lane: "SLEEP", premise: "planning your whole life at 2am and forgetting it by 9", photo: "person thinking in bed" },
  { lane: "SLEEP", premise: "sleeping through an earthquake but waking at one notification", photo: "phone buzzing nightstand" },
  { lane: "SLEEP", premise: "the heroic effort of getting up to turn the light off", photo: "bedroom light switch" },
  { lane: "SLEEP", premise: "drinking coffee at 9pm and being shocked you are awake", photo: "coffee cup evening" },
  { lane: "SLEEP", premise: "your weekend lie-in being interrupted by absolutely nothing", photo: "empty bedroom morning" },
  { lane: "SLEEP", premise: "the nap that ruins your entire night", photo: "person asleep on couch" },
  { lane: "SLEEP", premise: "getting comfortable and then needing the bathroom", photo: "cosy bed blanket" },
  { lane: "SLEEP", premise: "eight hours of sleep feeling like a personal achievement", photo: "person stretching morning" },
  { lane: "SLEEP", premise: "the alarm sound giving you a physical reaction now", photo: "alarm clock ringing" },
  { lane: "SLEEP", premise: "lying down and suddenly remembering every mistake you made", photo: "person lying in bed dark" },
  { lane: "SLEEP", premise: "your sleep schedule being a suggestion at this point", photo: "messy bed morning" },
  { lane: "SLEEP", premise: "waking up at 3am to check the time and nothing else", photo: "clock glowing dark room" },
  { lane: "SLEEP", premise: "being wide awake on the commute after fighting sleep all night", photo: "person on train commute" },

  // --- FOOD: eating, cooking, takeaways ------------------------------------
  { lane: "FOOD", premise: "ordering takeaway with a full fridge", photo: "takeaway food delivery" },
  { lane: "FOOD", premise: "the first bite of a meal you waited an hour for", photo: "person eating burger" },
  { lane: "FOOD", premise: "saying you will cook this week and ordering on day one", photo: "empty kitchen counter" },
  { lane: "FOOD", premise: "the last slice of pizza and the standoff around it", photo: "last slice of pizza" },
  { lane: "FOOD", premise: "eating a salad and immediately needing real food", photo: "bowl of salad" },
  { lane: "FOOD", premise: "the leftovers you were saving being gone", photo: "empty food container fridge" },
  { lane: "FOOD", premise: "burning the one thing you actually know how to cook", photo: "burnt pan kitchen" },
  { lane: "FOOD", premise: "grocery shopping hungry and buying a whole aisle", photo: "full shopping trolley" },
  { lane: "FOOD", premise: "the snack you hid from yourself being found by someone else", photo: "chocolate bar drawer" },
  { lane: "FOOD", premise: "tasting something suspicious instead of just throwing it away", photo: "person smelling milk carton" },
  { lane: "FOOD", premise: "the 3pm snack that becomes dinner", photo: "snacks on desk" },
  { lane: "FOOD", premise: "waiting for the microwave with the intensity of a scientist", photo: "microwave kitchen" },
  { lane: "FOOD", premise: "the one pan that makes everything taste better", photo: "cooking pan stove" },
  { lane: "FOOD", premise: "a recipe saying 'simple' and having 31 ingredients", photo: "cookbook kitchen counter" },
  { lane: "FOOD", premise: "eating standing up over the sink like an animal", photo: "kitchen sink counter" },
  { lane: "FOOD", premise: "the moment you realise you forgot the sauce", photo: "fries on a plate" },
  { lane: "FOOD", premise: "cereal at 11pm being a completely valid meal", photo: "bowl of cereal night" },
  { lane: "FOOD", premise: "meal prepping on Sunday and hating it by Tuesday", photo: "meal prep containers" },
  { lane: "FOOD", premise: "the specific betrayal of a soggy chip", photo: "french fries close up" },
  { lane: "FOOD", premise: "everyone agreeing on food being the hardest negotiation", photo: "friends looking at menu" },
  { lane: "FOOD", premise: "your coffee order being longer than your name", photo: "coffee shop counter" },
  { lane: "FOOD", premise: "buying vegetables to watch them slowly die", photo: "vegetables in fridge" },
  { lane: "FOOD", premise: "the fear of the first sip being too hot", photo: "hot cup of tea" },
  { lane: "FOOD", premise: "leftovers tasting better the next day for no reason", photo: "leftover food container" },
  { lane: "FOOD", premise: "the crumbs at the bottom of the packet being the best part", photo: "empty crisp packet" },
  { lane: "FOOD", premise: "saying 'I'm not hungry' then eating half their plate", photo: "two plates restaurant table" },
  { lane: "FOOD", premise: "opening the fridge for the eighth time in an hour", photo: "person opening fridge" },
  { lane: "FOOD", premise: "the delivery app tracker lying directly to your face", photo: "phone food delivery app" },
  { lane: "FOOD", premise: "bread going stale in 20 minutes but biscuits lasting a decade", photo: "loaf of bread kitchen" },
  { lane: "FOOD", premise: "putting something in the oven and forgetting it exists", photo: "oven kitchen" },
  { lane: "FOOD", premise: "the emotional damage of a dropped ice cream", photo: "ice cream cone" },
  { lane: "FOOD", premise: "someone taking a chip without asking", photo: "plate of chips sharing" },
  { lane: "FOOD", premise: "drinking water only when you see someone else drink water", photo: "glass of water table" },
  { lane: "FOOD", premise: "the mystery container at the back of the fridge", photo: "containers in fridge" },
  { lane: "FOOD", premise: "cooking for one and producing enough for nine", photo: "large pot of food" },

  // --- MONEY: being broke, bills, spending ---------------------------------
  { lane: "MONEY", premise: "your balance right after payday versus three days later", photo: "empty wallet" },
  { lane: "MONEY", premise: "a subscription you forgot about charging you for two years", photo: "credit card phone" },
  { lane: "MONEY", premise: "checking your bank app with one eye closed", photo: "person looking at phone worried" },
  { lane: "MONEY", premise: "'it's only a few pounds' eleven separate times", photo: "coins on a table" },
  { lane: "MONEY", premise: "the delivery fee costing more than the food", photo: "food delivery bag" },
  { lane: "MONEY", premise: "budgeting perfectly and then seeing one sale", photo: "sale shop window" },
  { lane: "MONEY", premise: "saving for something important and buying something stupid", photo: "shopping bags" },
  { lane: "MONEY", premise: "your savings account being a holding pen before a big purchase", photo: "piggy bank" },
  { lane: "MONEY", premise: "the free trial ending at the worst possible moment", photo: "laptop subscription screen" },
  { lane: "MONEY", premise: "splitting a bill with someone who ordered three courses", photo: "restaurant bill table" },
  { lane: "MONEY", premise: "clothes you bought that still have tags on", photo: "clothes on hangers" },
  { lane: "MONEY", premise: "the gym membership funding someone else's gym", photo: "empty gym equipment" },
  { lane: "MONEY", premise: "buying something to fix a problem you created by buying something", photo: "packages on doorstep" },
  { lane: "MONEY", premise: "your online basket being a museum you visit for fun", photo: "laptop online store" },
  { lane: "MONEY", premise: "petrol prices making you drive gently out of respect", photo: "petrol pump car" },
  { lane: "MONEY", premise: "the heating bill making you wear a coat indoors", photo: "person in coat inside home" },
  { lane: "MONEY", premise: "finding a fiver in a coat and feeling genuinely wealthy", photo: "banknote in hand" },
  { lane: "MONEY", premise: "your 'treat yourself' being the same treat every week", photo: "coffee cup takeaway" },
  { lane: "MONEY", premise: "a small purchase being fine and a big one being an existential crisis", photo: "credit card payment" },
  { lane: "MONEY", premise: "the rent going up for absolutely no visible reason", photo: "apartment building" },
  { lane: "MONEY", premise: "adding things to the basket to reach free delivery", photo: "online shopping phone" },
  { lane: "MONEY", premise: "the exact moment the card machine says declined", photo: "card payment terminal" },
  { lane: "MONEY", premise: "having money and having money for that being different things", photo: "wallet with cash" },
  { lane: "MONEY", premise: "buying a water bottle to save money on water bottles", photo: "reusable water bottle" },
  { lane: "MONEY", premise: "your future self dealing with this, allegedly", photo: "stack of unopened letters" },
  { lane: "MONEY", premise: "the supermarket own brand doing 90 percent of the job", photo: "supermarket shelf products" },
  { lane: "MONEY", premise: "a one pound difference changing your entire decision", photo: "price tags shop" },
  { lane: "MONEY", premise: "paying for storage for things you will never use", photo: "storage boxes garage" },
  { lane: "MONEY", premise: "the tiny joy of an unexpected refund", photo: "phone bank notification" },
  { lane: "MONEY", premise: "seeing the total at checkout and reconsidering your life", photo: "supermarket checkout" },
  { lane: "MONEY", premise: "a free thing being the best thing you own", photo: "old mug on desk" },
  { lane: "MONEY", premise: "the app telling you that you spent more on coffee than transport", photo: "banking app phone" },
  { lane: "MONEY", premise: "buying a planner to organise a life you will not organise", photo: "new planner notebook" },
  { lane: "MONEY", premise: "the moment a 'small' repair quote arrives", photo: "car mechanic garage" },
  { lane: "MONEY", premise: "your loyalty card having two stamps for six years", photo: "loyalty card coffee shop" },

  // --- ANIMALS: cats, dogs, wholesome chaos --------------------------------
  { lane: "ANIMALS", premise: "a cat deliberately knocking a glass off a table while maintaining eye contact", photo: "cat on a table" },
  { lane: "ANIMALS", premise: "a dog acting like you were gone for nine years", photo: "excited dog greeting" },
  { lane: "ANIMALS", premise: "a cat sitting in the box instead of the expensive bed", photo: "cat in cardboard box" },
  { lane: "ANIMALS", premise: "a dog hearing the word 'walk' from another room", photo: "dog with leash" },
  { lane: "ANIMALS", premise: "a cat sleeping 20 hours and still looking exhausted", photo: "sleeping cat" },
  { lane: "ANIMALS", premise: "a dog carrying one enormous stick with total pride", photo: "dog with stick park" },
  { lane: "ANIMALS", premise: "a cat sitting on the exact thing you are using", photo: "cat on laptop keyboard" },
  { lane: "ANIMALS", premise: "a dog's face when the vet building comes into view", photo: "dog in car window" },
  { lane: "ANIMALS", premise: "a cat staring at a wall at 3am for its own reasons", photo: "cat staring at wall" },
  { lane: "ANIMALS", premise: "a dog that thinks it is a lap dog and is not", photo: "big dog on lap sofa" },
  { lane: "ANIMALS", premise: "a cat being deeply offended by a new haircut", photo: "cat looking annoyed" },
  { lane: "ANIMALS", premise: "a dog watching you eat with full emotional manipulation", photo: "dog begging at table" },
  { lane: "ANIMALS", premise: "a cat knowing exactly when you are about to leave", photo: "cat sitting by door" },
  { lane: "ANIMALS", premise: "a puppy losing a fight with a blanket", photo: "puppy playing blanket" },
  { lane: "ANIMALS", premise: "a cat refusing the food it loved yesterday", photo: "cat with food bowl" },
  { lane: "ANIMALS", premise: "a dog who has found one puddle in a dry park", photo: "muddy dog park" },
  { lane: "ANIMALS", premise: "a cat's tail doing all the emotional communication", photo: "cat tail close up" },
  { lane: "ANIMALS", premise: "a dog meeting another dog like it is a festival", photo: "two dogs meeting park" },
  { lane: "ANIMALS", premise: "a cat making a sound you have never heard before", photo: "cat meowing" },
  { lane: "ANIMALS", premise: "a dog falling asleep mid-sit", photo: "dog sleeping sitting" },
  { lane: "ANIMALS", premise: "a cat walking across you at 5am with purpose", photo: "cat on bed morning" },
  { lane: "ANIMALS", premise: "a dog being suspicious of a completely normal object", photo: "dog staring at object" },
  { lane: "ANIMALS", premise: "a cat that hates everyone except one random guest", photo: "cat sitting on stranger lap" },
  { lane: "ANIMALS", premise: "a dog who thinks the postman is a recurring villain", photo: "dog at window looking out" },
  { lane: "ANIMALS", premise: "a cat fitting into a container it should not fit into", photo: "cat in small basket" },
  { lane: "ANIMALS", premise: "a dog's ears when it hears a crisp packet", photo: "alert dog ears up" },
  { lane: "ANIMALS", premise: "a cat judging your entire life from a shelf", photo: "cat on shelf looking down" },
  { lane: "ANIMALS", premise: "a dog that has to bring a toy to every single greeting", photo: "dog holding toy" },
  { lane: "ANIMALS", premise: "a cat in a sunbeam ignoring all responsibilities", photo: "cat in sunlight window" },
  { lane: "ANIMALS", premise: "a dog attempting to sit on a seat clearly too small", photo: "dog sitting in small chair" },
  { lane: "ANIMALS", premise: "a cat that comes running only when a tin opens", photo: "cat running kitchen" },
  { lane: "ANIMALS", premise: "a dog's guilt face before you have found anything", photo: "guilty looking dog" },
  { lane: "ANIMALS", premise: "a cat sleeping on the one clean pile of laundry", photo: "cat on folded laundry" },
  { lane: "ANIMALS", premise: "a dog who has decided the sofa is legally his", photo: "dog lying on sofa" },
  { lane: "ANIMALS", premise: "a cat watching birds and making the chattering noise", photo: "cat looking out window" },
];

/** Every distinct lane present in the seed bank. */
export function seedLanes(): string[] {
  return [...new Set(SEEDS.map((s) => s.lane))];
}
